CREATE TABLE ASSISTS_CUSTOMER (
    E_ID            INT             NOT NULL,
    C_ID            INT             NOT NULL,
    PRIMARY KEY(E_ID, C_ID),
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(Employee_ID)
        ON DELETE CASCADE   ON UPDATE CASCADE,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(Customer_ID)
        ON DELETE CASCADE   ON UPDATE CASCADE
);
